# Generated by Django 5.2.4 on 2025-07-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saree',
            name='image_url',
        ),
        migrations.AddField(
            model_name='saree',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='sarees/'),
            preserve_default=False,
        ),
    ]
