# Generated by Django 5.2.4 on 2025-07-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_saree_sareeimage_delete_product_order_saree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saree',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='saree',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='saree',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sareeimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sareeimage',
            name='image',
            field=models.ImageField(upload_to='saree_images/'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
