# Generated by Django 5.2.4 on 2025-07-08 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_saree_description_alter_saree_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saree',
            name='main_image',
            field=models.ImageField(default=11, upload_to='sarees/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saree',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='saree',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='saree',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='saree',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sareeimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sareeimage',
            name='image',
            field=models.ImageField(upload_to='sarees/'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.saree')),
            ],
        ),
    ]
