# Generated by Django 5.2.4 on 2025-08-06 12:45

from django.db import migrations, models


def copy_main_image_to_image1(apps, schema_editor):
    """Copy existing main_image data to image1 field"""
    Saree = apps.get_model('products', 'Saree')
    for saree in Saree.objects.all():
        if saree.main_image:
            saree.image1 = saree.main_image
            saree.save()


def reverse_copy_image1_to_main_image(apps, schema_editor):
    """Reverse operation: copy image1 back to main_image"""
    Saree = apps.get_model('products', 'Saree')
    for saree in Saree.objects.all():
        if saree.image1:
            saree.main_image = saree.image1
            saree.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order_guest_address_order_guest_email_and_more'),
    ]

    operations = [
        # First add the new image fields
        migrations.AddField(
            model_name='saree',
            name='image1',
            field=models.ImageField(blank=True, help_text='Main image (required)', null=True, upload_to='sarees/'),
        ),
        migrations.AddField(
            model_name='saree',
            name='image2',
            field=models.ImageField(blank=True, help_text='Second image (optional)', null=True, upload_to='sarees/'),
        ),
        migrations.AddField(
            model_name='saree',
            name='image3',
            field=models.ImageField(blank=True, help_text='Third image (optional)', null=True, upload_to='sarees/'),
        ),
        # Copy existing main_image data to image1
        migrations.RunPython(copy_main_image_to_image1, reverse_copy_image1_to_main_image),
        # Finally remove the old main_image field
        migrations.RemoveField(
            model_name='saree',
            name='main_image',
        ),
    ]
