# Generated by Django 5.2.4 on 2025-08-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_add_multiple_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saree',
            old_name='image1',
            new_name='main_image',
        ),
        migrations.RemoveField(
            model_name='saree',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='saree',
            name='image3',
        ),
        migrations.AddField(
            model_name='saree',
            name='extra_image1',
            field=models.ImageField(blank=True, help_text='Extra image 1 (optional)', null=True, upload_to='sarees/'),
        ),
        migrations.AddField(
            model_name='saree',
            name='extra_image2',
            field=models.ImageField(blank=True, help_text='Extra image 2 (optional)', null=True, upload_to='sarees/'),
        ),
        migrations.AddField(
            model_name='saree',
            name='extra_image3',
            field=models.ImageField(blank=True, help_text='Extra image 3 (optional)', null=True, upload_to='sarees/'),
        ),
    ]
