# Generated by Django 5.2.4 on 2026-04-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_coupon_saree_created_at_saree_is_best_seller_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-priority', 'name']},
        ),
        migrations.AddField(
            model_name='collection',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saree',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='saree',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='saree',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='collections', to='products.saree'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
