# Generated by Django 5.2.4 on 2026-04-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_collection_options_collection_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Vijayalakshmi Silks', max_length=200)),
                ('contact_phone', models.CharField(default='+91 97915 79731', max_length=20)),
                ('whatsapp_number', models.CharField(default='+91 97915 79731', max_length=20)),
                ('email', models.EmailField(default='kishore.kumar0728@gmail.com', max_length=254)),
                ('address', models.TextField(default='Kanchipuram, Tamil Nadu, India')),
                ('business_hours', models.CharField(default='Mon - Sat: 9:00 AM - 8:00 PM', max_length=200)),
                ('free_delivery_min', models.PositiveIntegerField(default=999)),
                ('delivery_charge', models.PositiveIntegerField(default=100)),
                ('enable_free_delivery', models.BooleanField(default=True)),
                ('est_delivery_time', models.CharField(default='5-7 Business Days', max_length=100)),
                ('razorpay_enabled', models.BooleanField(default=True)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('cod_charge', models.PositiveIntegerField(default=50)),
                ('min_order_value', models.PositiveIntegerField(default=0)),
                ('max_order_qty', models.PositiveIntegerField(default=5)),
                ('allow_guest_checkout', models.BooleanField(default=True)),
                ('auto_confirm_orders', models.BooleanField(default=False)),
                ('hero_tagline', models.CharField(default='Authentic Kanchipuram Heritage', max_length=255)),
                ('hero_description', models.TextField(default='Experience the timeless elegance of handpicked pure silk sarees.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('hero_image_1', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('hero_image_2', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('show_collections', models.BooleanField(default=True)),
                ('show_story', models.BooleanField(default=True)),
                ('show_stats', models.BooleanField(default=True)),
                ('whatsapp_order_placed', models.BooleanField(default=True)),
                ('whatsapp_order_shipped', models.BooleanField(default=True)),
                ('default_meta_title', models.CharField(default='Vijayalakshmi Silks | Pure Kanchipuram Silk Sarees', max_length=200)),
                ('default_meta_description', models.TextField(default='Handpicked pure silk sarees from Kanchipuram.')),
                ('default_keywords', models.CharField(default='silk sarees, kanchipuram, handloom, wedding sarees', max_length=500)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, help_text='e.g. BlueDart, Delhivery', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
