# Generated by Django 5.2.4 on 2026-04-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_sitesettings_order_courier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_footer',
            field=models.TextField(default='Thank you for choosing Vijayalakshmi Silks. We hope you cherish this heritage piece.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_notes',
            field=models.TextField(default='For support, contact: support@vijayalakshmisilks.com'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_prefix',
            field=models.CharField(default='ORD', max_length=20),
        ),
    ]
