# Generated by Django 5.2.4 on 2026-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_sitesettings_invoice_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saree',
            name='mrp',
            field=models.PositiveIntegerField(blank=True, help_text='Original price (Maximum Retail Price)', null=True),
        ),
    ]
