# Generated by Django 5.2.4 on 2026-04-28 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_saree_mrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('content', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='saree',
            name='canonical_override',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saree',
            name='highlights',
            field=models.TextField(blank=True, help_text='Enter bullet points separated by newlines'),
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('saree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.saree')),
            ],
        ),
    ]
