# Generated by Django 5.2.4 on 2026-04-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_blogpost_saree_canonical_override_saree_highlights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saree',
            name='is_authentic_silk',
            field=models.BooleanField(default=True),
        ),
    ]
