# Generated by Django 5.2.4 on 2026-04-29 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_saree_is_authentic_silk'),
    ]

    operations = [
        migrations.AddField(
            model_name='saree',
            name='video',
            field=models.FileField(blank=True, help_text='Product showcase video (optional)', null=True, upload_to='videos/'),
        ),
        migrations.CreateModel(
            name='SareeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload additional product image', upload_to='sarees/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.saree')),
            ],
        ),
    ]
