# Generated by Django 5.2.4 on 2026-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_saree_video_sareeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_delivery_all_orders',
            field=models.BooleanField(default=False),
        ),
    ]
