# Generated by Django 5.2.4 on 2026-04-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_sitesettings_free_delivery_all_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
