# Generated by Django 5.2.4 on 2026-04-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_sitesettings_hero_image_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_sms_notifications',
            field=models.BooleanField(default=False, help_text='Enable Twilio SMS notifications for orders'),
        ),
    ]
