# Generated by Django 5.2.4 on 2026-04-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_sitesettings_enable_sms_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='twilio_account_sid',
            field=models.CharField(blank=True, help_text='Twilio Account SID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twilio_auth_token',
            field=models.CharField(blank=True, help_text='Twilio Auth Token', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twilio_phone_number',
            field=models.CharField(blank=True, help_text='Twilio Phone Number (e.g. +1234567890)', max_length=20, null=True),
        ),
    ]
