# Generated by Django 5.2.4 on 2026-04-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_sitesettings_twilio_account_sid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_phone',
            field=models.CharField(default='+919791579731', help_text='Phone number to receive new order alerts (e.g. +919876543210)', max_length=20),
        ),
    ]
