# Generated by Django 5.2.4 on 2025-07-05 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_saree_image_url_saree_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saree',
            name='image',
        ),
        migrations.AddField(
            model_name='saree',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SareeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='saree_images/')),
                ('saree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.saree')),
            ],
        ),
    ]
