# Generated by Django 5.2.4 on 2025-07-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_saree_image_saree_description_sareeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.RemoveField(
            model_name='sareeimage',
            name='saree',
        ),
        migrations.DeleteModel(
            name='Saree',
        ),
        migrations.DeleteModel(
            name='SareeImage',
        ),
    ]
